version: '3'

services:
  creaturesncaves:
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      NODE_ENV: production
      REACT_APP_SERVER_ADDRESS: http://localhost:5000
    ports:
      - "8080:80"