name: Deploy to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Connection String
        uses: microsoft/variable-substitution@v1
        with:
          files: Server/appsettings.json
        env:
          ConnectionStrings.DBConnectionString: ${{ secrets.DATABASE_CONNECTION_STRING }}

      - name: Build docker image
        run: docker build -t cnc:latest .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cnc'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: cnc:latest
          configuration-file: docker-compose.yml
  