name: Creatures & Caves Master Pipeline

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run ClientApp unit tests
      run: docker build -t cnc/clientapptests:latest --target node-test-env .  
    
    - name: Extract ClientApp Coverage Reports
      run: |
        CID=$(docker create cnc/clientapptests:latest)
        mkdir -p TestResults
        docker cp $CID:/ClientApp/coverage/. - > TestResults/clientappreports.tar
        docker rm -v $CID
        cd TestResults
        tar -xvf clientappreports.tar
        
    - name: Run Server unit tests
      run: docker build -t cnc/servertests:latest --target dotnet-test-env .  
    
    - name: Extract Server Coverage Reports
      run: |
        CID=$(docker create cnc/servertests:latest)
        mkdir -p TestResults
        docker cp $CID:/Server.Tests/TestResults/. - > TestResults/serverreports.tar
        docker rm -v $CID
        cd TestResults
        tar -xvf serverreports.tar
        
    - name: Upload Test Results Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: TestResults
        # Directory containing files to upload
        path: TestResults
              
    - name: Upload ClientApp TestResults to Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # User defined upload name. Visible in Codecov UI
        name: ClientApp
        # Repository upload token - get it from codecov.io
        token: c148f571-5080-4421-b1ec-72a4d397a7db
        # Path to coverage file to upload
        file: Artifacts/TestResults/coverage-final.json
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: unittests
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
        
    - name: Upload Server TestResults to Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # User defined upload name. Visible in Codecov UI
        name: Server
        # Repository upload token - get it from codecov.io
        token: c148f571-5080-4421-b1ec-72a4d397a7db
        # Path to coverage file to upload
        file: Artifacts/TestResults/coverage.json
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: unittests
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true

  
