name: Creatures & Caves Master Pipeline

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run ClientApp unit tests
      run: docker build -t cnc/clientapptests:latest --target node-test-env .  
    
    - name: Extract ClientApp Coverage Reports
      run: |
        CID=$(docker create cnc/clientapptests:latest)
        mkdir -p TestResults
        docker cp $CID:/ClientApp/coverage - > TestResults/ClientApp
        docker rm -v $CID
        
    - name: Run Server unit tests
      run: docker build -t cnc/servertests:latest --target dotnet-test-env .  
    
    - name: Extract Server Coverage Reports
      run: |
        CID=$(docker create cnc/servertests:latest)
        mkdir -p TestResults
        docker cp $CID:/Server.Tests/TestResults - > TestResults/Server
        docker rm -v $CID
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: TestResults
        # Directory containing files to upload
        path: TestResults
          
        
  
