name: Test Pipeline

on:
  pull_request:
    branches: 
      - master

jobs:
  
  test frontend:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run Frontend unit tests
      run: docker build -t cnc/frontendtests:latest --target node-test-env .  
    
    - name: Extract Frontend Coverage Reports
      run: |
        CID=$(docker create cnc/frontendtests:latest)
        mkdir -p TestResults
        docker cp $CID:/ClientApp/coverage/. - > TestResults/frontend-test-report.tar
        docker rm -v $CID
        cd TestResults
        tar -xvf frontend-test-report.tar
        mv coverage-final.json frontend.json 
        
    - name: Upload Test Results Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Frontend_TestResults
        # Directory containing files to upload
        path: TestResults
              
    - name: Upload ClientApp TestResults to Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # User defined upload name. Visible in Codecov UI
        name: ClientApp
        # Repository upload token - get it from codecov.io
        token: ${{ secrets.CODECOV_TOKEN }}
        # Path to coverage file to upload
        file: TestResults/frontend.json
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: unittests
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
        
  test-backend:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Backend Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
              
    - name: Run Backend unit tests
      run: docker build -t cnc/backendtests:latest --target dotnet-test-env .  
    
    - name: Extract Backend Coverage Reports
      run: |
        CID=$(docker create cnc/backendtests:latest)
        mkdir -p TestResults
        docker cp $CID:/Server.Tests/TestResults/. - > TestResults/server-test-report.tar
        docker cp $CID:/EntityFramework.Tests/TestResults/. - > TestResults/entityframework-test-report.tar
        docker rm -v $CID
        cd TestResults
        tar -xvf entityframework-test-report.tar
        mv coverage.opencover.xml entityframework.opencover.xml
        tar -xvf server-test-report.tar 
        mv coverage.opencover.xml server.opencover.xml        
        
    - name: Upload Test Results Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Backend_TestResults
        # Directory containing files to upload
        path: TestResults
                      
    - name: Upload Server TestResults to Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # User defined upload name. Visible in Codecov UI
        name: Server
        # Repository upload token - get it from codecov.io
        token: ${{ secrets.CODECOV_TOKEN }}
        # Path to coverage file to upload
        file: TestResults/server.opencover.xml
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: unittests
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
        
    - name: Upload EntityFramework TestResults to Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # User defined upload name. Visible in Codecov UI
        name: EntityFramework
        # Repository upload token - get it from codecov.io
        token: ${{ secrets.CODECOV_TOKEN }}
        # Path to coverage file to upload
        file: TestResults/entityframework.opencover.xml
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: unittests
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
